@startuml
start
:Speler kiest actie;
if (Klik op cel?) then (ja)
  if (Cel is al onthuld?) then (ja)
    :Geen actie;
  else (nee)
    if (Cel is gemarkeerd met vlag?) then (ja)
      :Geen actie;
    else (nee)
      if (Cel is mijn?) then (ja)
        :Toon alle mijnen;
        :Toon verliesmelding;
        :Speel verlies-geluid;
        stop
      else (nee)
        :Onthul cel;
        if (Cel is leeg?) then (ja)
          :Onthul buren;
        else (nee)
          ' Geen extra actie nodig
        endif
        :Update bord;
        if (Gewonnen?) then (ja)
          :Toon winmelding;
          :Speel win-geluid;
          :Toon confetti;
          stop
        else (nee)
          ' Spel gaat verder
        endif
      endif
    endif
  endif
else (nee)
  if (Plaats vlag?) then (ja)
    if (Cel is al onthuld?) then (ja)
      :Geen actie;
    else (nee)
      :Vlag plaatsen/verwijderen;
    endif
  else (nee)
    if (Herstart spel?) then (ja)
      :Reset bord;
      :Start nieuw spel;
    else (nee)
      :Wacht op volgende actie;
    endif
  endif
endif
stop
@enduml